baseURL = "http://blog.orionpax.top"
languageCode = "zh-cn"
defaultContentLanguage = "zh-cn"
title = "OrionPax 的个人博客"                    # site title  # 网站标题
theme = "zozo"
hasCJKLanguage = true                # has chinese/japanese/korean ? # 自动检测是否包含 中文\日文\韩文
summaryLength = 100
paginate = 5                         # shows the number of articles  # 首页显示文章数量
enableEmoji = true
googleAnalytics = ""                 # your google analytics id
disqusShortname = ""                 # your discuss shortname
publishdir = "./"
contentdir = "content"

[author]                             # essential                     # 必需
  name = "OrionPax"

[sitemap]                 # essential                     # 必需
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"

[blackfriday]
  smartypants = false

[[menu.main]]
  name = "归档"
  weight = 20
  identifier = "archive"
  url = "/posts/"
[[menu.main]]
  name = "标签"
  weight = 30
  identifier = "tags"
  url = "/tags/"
[[menu.main]]
  name = "技能树"
  weight = 40
  identifier = "skills"
  url = "/skills.png"
[[menu.main]]
  name = "工具栈"
  weight = 50
  identifier = "tools"
  url = "/Tools.png"

[params]
  footerSlogan = "不能记住过去的人，被判重复过去。"                                          # site's footer slogan  # 网站页脚标语
  keywords = ["OrionPax", "Java 开发", "Hugo","zozo"]                                  # site's keywords  # 网站关键字
  description = "个人博客小站"                        # site's description  # 网站描述

# mathjax
  enableMathJax = true                                                 # enable mathjax  # 是否使用mathjax（数学公式）
  enableSummary = true                                                 # display the article summary  # 是否显示文章摘要

# paginate of archives, tags and categories             # 归档、标签、分类每页显示的文章数目，建议修改为一个较大的值
archivePaginate = 25

# show 'xx Posts In Total' in archive page ?            # 是否在归档页显示文章的总数
showArchiveCount = true

# show word count and read time ?                       # 是否显示字数统计与阅读时间
moreMeta = true

# Syntax highlighting by highlight.js
highlightInClient = true

# 一些全局开关，你也可以在每一篇内容的 front matter 中针对单篇内容关闭或开启某些功能，在 archetypes/default.md 查看更多信息。
# Some global options, you can also close or open something in front matter for a single post, see more information from `archetypes/default.md`.
toc = true                                                                            # 是否开启目录
autoCollapseToc = false   # Auto expand and collapse toc                              # 目录自动展开/折叠
fancybox = true           # see https://github.com/fancyapps/fancybox                 # 是否启用fancybox（图片可点击）
  
# Valine.
# You can get your appid and appkey from https://leancloud.cn
# more info please open https://valine.js.org
[params.valine]
  enable = true
  appId = "nW05u87yweVedDRhj6AUgzR1-gzGzoHsz"
  appKey = "4HgKbiggTv7ocU789S5WO6ov"
  placeholder = "确定不说点什么?"
  visitor = true

[params.busuanzi]         # count web traffic by busuanzi                             # 是否使用不蒜子统计站点访问量
  enable = true
  siteUV = true
  sitePV = true
  pagePV = true

[social]
  github = "https://github.com/OrionPax19970905"
  gmail = "OrionPax19970905@gmail.com"
